// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  details: dynamic(() => import("./Details")),
  hero: dynamic(() => import("./Hero")),
};
